AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  fbo-lambdas
  
  SAM Template for fbo-lambdas

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 60
    MemorySize: 192

Resources:
  Getter:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Runtime: java11-maven-v1
    Properties:
      PackageType: Image
      Architectures:
        - x86_64
      Events:
        GetAllCountries:
          Type: HttpApi # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#HttpApi
          Properties:
            Path: /countries
            Method: GET
        GetCountryByCode:
          Type: HttpApi # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#HttpApi
          Properties:
            Path: /countries/{code}
            Method: GET
        GetAllCurrencies:
          Type: HttpApi # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#HttpApi
          Properties:
            Path: /currencies
            Method: GET
        GetCurrencyByCode:
          Type: HttpApi # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#HttpApi
          Properties:
            Path: /currencies/{code}
            Method: GET
        GetAllCountriesCurrency:
          Type: HttpApi # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#HttpApi
          Properties:
            Path: /countries-currency
            Method: GET
        GetCountriesByCurrencyCode:
          Type: HttpApi # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#HttpApi
          Properties:
            Path: /countries-currency/{code}
            Method: GET
      Environment:
        Variables:
          REDIS_HOST: 'host.docker.internal'
          REDIS_PORT: 6379
          REDIS_DB: '0'
          REDIS_COUNTRY_KEY: 'key-countries'
          REDIS_CURRENCY_KEY: 'key-currencies'
    Metadata:
      DockerTag: java11-maven-v1
      DockerContext: ./GetterFunction
      Dockerfile: Dockerfile

    ApiGateway:
      Type: AWS::Serverless::Api
      Properties:
        StageName: dev
        DefinitionBody:
          swagger: "2.0"
          info:
            title:
            Ref: AWS::StackName
            description: ISO Countries API
            version: 1.0.0
